### ISSUE TITLE
Switching cameras shuts down the video loop

### ISSUE THREAD

**Issue by RastislavKish** [flying-pizza-69/GestureX#8]
There is a data race between the UI, particularly the camera selection dropdown, and the video loop.

## Reproduction steps

1. In the run_video_loop method of the main window class, add a debug printout to the end announcing when the method exits
2. Open the app on a system having two cameras at least
3. Switch cameras around

## Expected behavior

The video source should be swapped properly.

## Actual behavior

Between self.cap.release() and assigning a new camera to self.cap in on_camera_changed, run_video-loop fails to read the released camera source and breaks the loop. As a consequence, gestures are no longer detected.

**Comment by flying-pizza-69** [comment]
let me know if multiple cameras work for you now

**Comment by RastislavKish** [comment]
Yup, tested and it works great!
